#### Importing the Libraries:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Question 1:

* Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.


* HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

#### Solution:

My approach to create such function would be:

* Iterating over the array given for N(number of columns i.e. given) number of times for both cases.
* If increasing = False i.e default, raising each element to power = N-i-1.
* Else if increasing = True, raising each element to power i.
* Finally, reshaping the matrix in the shape(size of array, N)

In [29]:
def vander_matrix(arr, N , increasing = False):
    '''
    Returns a matrix whose columns are power of input vector.
    When increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
    '''
    if not increasing:
        mat = np.array([x**(N-i-1) for x in arr for i in range(N)]).reshape(arr.size,N)
    elif increasing:
        mat = np.array([x**i for x in arr for i in range(N)]).reshape(arr.size,N)
    
    return mat

##### Illustrating with an example:

In [30]:
arr = np.array([1, 2, 3, 5])
N = 3

print("The input array is:",arr,"\n")
print("Number of columns in output matrix should be:",N,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",vander_matrix(arr, N),"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",vander_matrix(arr, N, True),"\n")

The input array is: [1 2 3 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]] 



#### Question 2:

* Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
* The moving average sequence has n-k+1 elements as shown below.

* The moving averages with k=4 of a ten-value sequence (n=10) is shown below

* i 1 2 3 4 5 6 7 8 9 10
* ===== == == == == == == == == == ==
* Input 10 20 30 40 50 60 70 80 90 100
* y1 25 = (10+20+30+40)/4
* y2 35 = (20+30+40+50)/4
* y3 45 = (30+40+50+60)/4
* y4 55 = (40+50+60+70)/4
* y5 65 = (50+60+70+80)/4
* y6 75 = (60+70+80+90)/4
* y7 85 = (70+80+90+100)/4

* Thus, the moving average sequence has n-k+1=10-4+1=7 values.

* Question: Write a function to find moving average in an array over a window:
* Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [31]:
def moving_average(arr, w):
    
    mov_arr = []
    
    for i in range(len(arr) - w + 1):
        x = sum(arr[i:i+w])/w
        mov_arr.append(x)
    
    return np.array(mov_arr)

##### Testing it over solved example :

In [35]:
moving_average([10,20,30,40,50,60,70,80,90,100], 4)

array([25., 35., 45., 55., 65., 75., 85.])

##### Testing it over unsolved example !

In [33]:
moving_average([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])

# Done !