# Task 1:

## Question 1:

Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def Five_div_zero():
    try:
        return 5/0
    
    except ZeroDivisionError:
        print("Division by zero not allowed !!")

    except:
        print("An error has occured. Provide valid inputs")

In [2]:
Five_div_zero() # Due to ZeroDivisionError, first except statement will be executed !!

Division by zero not allowed !!


## Question 2:

* Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
* Hint: Subject,Verb and Object should be declared in the program as shown below.
* subjects = [ "Americans ","Indians" ]
* verbs = [ "play","watch" ]
* objects = [ "Baseball","Cricket" ]
* Output should come as below:
* Americans play Baseball.
* Americans play Cricket.
* Americans watch Baseball.
* Americans watch Cricket.
* Indians play Baseball.
* Indians play Cricket.
* Indians watch Baseball.
* Indians watch Cricket.

In [3]:
subjects = ["Americans","Indians"]
verbs = ["play","watch"]
objects = ["Baseball","Cricket"]

my_list = [sub + " " + verb + " " + obj for sub in subjects for verb in verbs for obj in objects]

for sentence in my_list:
    print(sentence)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2:

#### Question 1:

* Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.


* HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

#### Solution:

My approach to create such function would be:

* Iterating over the array given for N(number of columns i.e. given) number of times for both cases.
* If increasing = False i.e default, raising each element to power = N-i-1.
* Else if increasing = True, raising each element to power i.
* Finally, reshaping the matrix in the shape(size of array, N)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def vander_matrix(arr, N , increasing = False):
    '''
    Returns a matrix whose columns are power of input vector.
    When increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
    '''
    if not increasing:
        mat = np.array([x**(N-i-1) for x in arr for i in range(N)]).reshape(arr.size,N)
    elif increasing:
        mat = np.array([x**i for x in arr for i in range(N)]).reshape(arr.size,N)
    
    return mat

##### Illustrating with an example:

In [3]:
arr = np.array([1, 2, 3, 5])
N = 3

print("The input array is:",arr,"\n")
print("Number of columns in output matrix should be:",N,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",vander_matrix(arr, N),"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",vander_matrix(arr, N, True),"\n")

The input array is: [1 2 3 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]] 



# Done !